meta_product_name: "Spout"
meta_title: "Spout - Discover outdoor sports spots"
meta_description: "Avec Spout, explorez votre ville et découvrez les meilleurs spots de sport en extérieur grâce à la map interractive. Simplicité, efficacité, découverte.  "
meta_image: "Spout2.png" # should exist in `app/assets/images/`
